import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import AppBreadCrumb from "@/components/app-breadcrumb";
import { Toaster } from "@/components/ui/sonner";
import PlayButtons from "@/components/play-buttons";
import { AuthProvider, useAuth } from "@/components/AuthContext";
import LoginPage from "./login/page";
import AuthGate from "@/components/authgate";

export const metadata: Metadata = {
  title: "Trading Bot",
  description: "Generated by Vasyl",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <AuthGate>
            <SidebarProvider>
              <AppSidebar />
              <main className="w-full py-5 px-5">
                <div className="flex items-center gap-4">
                  <SidebarTrigger />
                  <AppBreadCrumb />
                  <PlayButtons />
                </div>
                {children}
              </main>
            </SidebarProvider>
          </AuthGate>
          <Toaster position="top-right" richColors />
        </AuthProvider>
      </body>
    </html>
  );
}
