import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import AppBreadCrumb from "@/components/app-breadcrumb";
import { Toaster } from "@/components/ui/sonner";
import PlayButtons from "@/components/play-buttons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trading Bot",
  description: "Generated by Vasyl",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full py-5 px-5">
            <div className="flex items-center gap-4">
              <SidebarTrigger />
              <AppBreadCrumb />
              <PlayButtons />
            </div>
            {children}
          </main>
          <Toaster position="top-center" richColors />
        </SidebarProvider>
      </body>
    </html>
  );
}
